name = "GeneticAlgorithms"
uuid = "9735efce-a0dd-4f8d-ab70-f8f6a41fe78d"
authors = ["Daniel Kirste <daniel.kirste@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
TestEnv = "1e6cf692-eddd-4d53-88a5-2d735e33781b"

[compat]
TestEnv = "1.102.0"
julia = "1.10"
